//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.24 at 02:56:50 PM QYZT 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralIdResponse", propOrder = {
        "id"
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public class GeneralIdResponse {
    @XmlElement(required = true)
    protected String id;
}
