//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.esp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DefectElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefectElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mis_id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.kaysat-ps.org}ServiceID"/&gt;
 *         &lt;element name="defect_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="date_defect" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="act" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="monitoring" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="expert_id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="vid_defect" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefectElement", propOrder = {
    "misId",
    "id",
    "defectId",
    "dateDefect",
    "act",
    "monitoring",
    "count",
    "expertId",
    "vidDefect"
})
public class DefectElement {

    @XmlElement(name = "mis_id")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger misId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;
    @XmlElement(name = "defect_id", required = true)
    protected String defectId;
    @XmlElement(name = "date_defect", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateDefect;
    @XmlElement(required = true)
    protected String act;
    protected int monitoring;
    protected int count;
    @XmlElement(name = "expert_id", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger expertId;
    @XmlElement(name = "vid_defect")
    protected int vidDefect;

    /**
     * Gets the value of the misId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMisId() {
        return misId;
    }

    /**
     * Sets the value of the misId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMisId(BigInteger value) {
        this.misId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the defectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefectId() {
        return defectId;
    }

    /**
     * Sets the value of the defectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefectId(String value) {
        this.defectId = value;
    }

    /**
     * Gets the value of the dateDefect property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDefect() {
        return dateDefect;
    }

    /**
     * Sets the value of the dateDefect property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDefect(XMLGregorianCalendar value) {
        this.dateDefect = value;
    }

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAct(String value) {
        this.act = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     */
    public int getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     */
    public void setMonitoring(int value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the expertId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpertId() {
        return expertId;
    }

    /**
     * Sets the value of the expertId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpertId(BigInteger value) {
        this.expertId = value;
    }

    /**
     * Gets the value of the vidDefect property.
     * 
     */
    public int getVidDefect() {
        return vidDefect;
    }

    /**
     * Sets the value of the vidDefect property.
     * 
     */
    public void setVidDefect(int value) {
        this.vidDefect = value;
    }

}
