//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.esp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.ezdrav.eps_smartbridge_adapter.model.ws.esp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.ezdrav.eps_smartbridge_adapter.model.ws.esp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FinanceSource }
     * 
     */
    public FinanceSource createFinanceSource() {
        return new FinanceSource();
    }

    /**
     * Create an instance of {@link FinanceBatch }
     * 
     */
    public FinanceBatch createFinanceBatch() {
        return new FinanceBatch();
    }

    /**
     * Create an instance of {@link GetCtrl }
     * 
     */
    public GetCtrl createGetCtrl() {
        return new GetCtrl();
    }

    /**
     * Create an instance of {@link ParamsDate }
     * 
     */
    public ParamsDate createParamsDate() {
        return new ParamsDate();
    }

    /**
     * Create an instance of {@link GetData2 }
     * 
     */
    public GetData2 createGetData2() {
        return new GetData2();
    }

    /**
     * Create an instance of {@link GetDataByIDs }
     * 
     */
    public GetDataByIDs createGetDataByIDs() {
        return new GetDataByIDs();
    }

    /**
     * Create an instance of {@link ParamsIDs }
     * 
     */
    public ParamsIDs createParamsIDs() {
        return new ParamsIDs();
    }

    /**
     * Create an instance of {@link GetDataByPeriod }
     * 
     */
    public GetDataByPeriod createGetDataByPeriod() {
        return new GetDataByPeriod();
    }

    /**
     * Create an instance of {@link GetIdByDate }
     * 
     */
    public GetIdByDate createGetIdByDate() {
        return new GetIdByDate();
    }

    /**
     * Create an instance of {@link GetIDs }
     * 
     */
    public GetIDs createGetIDs() {
        return new GetIDs();
    }

    /**
     * Create an instance of {@link GetReferral }
     * 
     */
    public GetReferral createGetReferral() {
        return new GetReferral();
    }

    /**
     * Create an instance of {@link GetRefferalByID }
     * 
     */
    public GetRefferalByID createGetRefferalByID() {
        return new GetRefferalByID();
    }

    /**
     * Create an instance of {@link GetRefferalByPeriod }
     * 
     */
    public GetRefferalByPeriod createGetRefferalByPeriod() {
        return new GetRefferalByPeriod();
    }

    /**
     * Create an instance of {@link GetRefferalByPerson }
     * 
     */
    public GetRefferalByPerson createGetRefferalByPerson() {
        return new GetRefferalByPerson();
    }

    /**
     * Create an instance of {@link GetServicesByDate }
     * 
     */
    public GetServicesByDate createGetServicesByDate() {
        return new GetServicesByDate();
    }

    /**
     * Create an instance of {@link SetData }
     * 
     */
    public SetData createSetData() {
        return new SetData();
    }

    /**
     * Create an instance of {@link ServicesBatch }
     * 
     */
    public ServicesBatch createServicesBatch() {
        return new ServicesBatch();
    }

    /**
     * Create an instance of {@link SetDataAmb }
     * 
     */
    public SetDataAmb createSetDataAmb() {
        return new SetDataAmb();
    }

    /**
     * Create an instance of {@link SetDefects }
     * 
     */
    public SetDefects createSetDefects() {
        return new SetDefects();
    }

    /**
     * Create an instance of {@link DefectsBatch }
     * 
     */
    public DefectsBatch createDefectsBatch() {
        return new DefectsBatch();
    }

    /**
     * Create an instance of {@link SetReferral }
     * 
     */
    public SetReferral createSetReferral() {
        return new SetReferral();
    }

    /**
     * Create an instance of {@link ChekList }
     * 
     */
    public ChekList createChekList() {
        return new ChekList();
    }

    /**
     * Create an instance of {@link IDRecord }
     * 
     */
    public IDRecord createIDRecord() {
        return new IDRecord();
    }

    /**
     * Create an instance of {@link FinanceElement }
     * 
     */
    public FinanceElement createFinanceElement() {
        return new FinanceElement();
    }

    /**
     * Create an instance of {@link DefectElement }
     * 
     */
    public DefectElement createDefectElement() {
        return new DefectElement();
    }

    /**
     * Create an instance of {@link ServiceElement }
     * 
     */
    public ServiceElement createServiceElement() {
        return new ServiceElement();
    }

}
