//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kaysat-ps.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.ezdrav.eps_smartbridge_adapter.model.ws.esp;
