//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.eps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChekList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChekList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="scrining_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chek_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chek_value" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChekList", propOrder = {
    "scriningId",
    "chekId",
    "chekValue"
})
public class ChekList {

    @XmlElement(name = "scrining_id", required = true)
    protected String scriningId;
    @XmlElement(name = "chek_id", required = true)
    protected String chekId;
    @XmlElement(name = "chek_value")
    protected int chekValue;

    /**
     * Gets the value of the scriningId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScriningId() {
        return scriningId;
    }

    /**
     * Sets the value of the scriningId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScriningId(String value) {
        this.scriningId = value;
    }

    /**
     * Gets the value of the chekId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChekId() {
        return chekId;
    }

    /**
     * Sets the value of the chekId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChekId(String value) {
        this.chekId = value;
    }

    /**
     * Gets the value of the chekValue property.
     * 
     */
    public int getChekValue() {
        return chekValue;
    }

    /**
     * Sets the value of the chekValue property.
     * 
     */
    public void setChekValue(int value) {
        this.chekValue = value;
    }

}
