//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.eps;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FinanceElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinanceElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="direction_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="service_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="icd_type" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ocd_code" type="{http://www.kaysat-ps.org}MKB10Code"/&gt;
 *         &lt;element name="direction_reason" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sended_mo" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="sending_mo" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="PatientStatus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="RpnIDMother" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="group_id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Place" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Parent_id" type="{http://www.kaysat-ps.org}ServiceID" minOccurs="0"/&gt;
 *         &lt;element name="ServiceKind2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Refferal_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Visit_type" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinanceElement", propOrder = {
    "id",
    "personId",
    "directionDate",
    "serviceCode",
    "icdType",
    "ocdCode",
    "directionReason",
    "sendedMo",
    "sendingMo",
    "patientStatus",
    "rpnIDMother",
    "groupId",
    "place",
    "parentId",
    "serviceKind2",
    "refferalId",
    "visitType"
})
public class FinanceElement {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "person_id", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger personId;
    @XmlElement(name = "direction_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar directionDate;
    @XmlElement(name = "service_code", required = true)
    protected String serviceCode;
    @XmlElement(name = "icd_type")
    protected int icdType;
    @XmlElement(name = "ocd_code", required = true)
    protected String ocdCode;
    @XmlElement(name = "direction_reason")
    protected int directionReason;
    @XmlElement(name = "sended_mo", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger sendedMo;
    @XmlElement(name = "sending_mo", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger sendingMo;
    @XmlElement(name = "PatientStatus")
    protected Integer patientStatus;
    @XmlElement(name = "RpnIDMother")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger rpnIDMother;
    @XmlElement(name = "group_id")
    protected Integer groupId;
    @XmlElement(name = "Place")
    protected String place;
    @XmlElement(name = "Parent_id")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger parentId;
    @XmlElement(name = "ServiceKind2")
    protected Boolean serviceKind2;
    @XmlElement(name = "Refferal_id")
    protected String refferalId;
    @XmlElement(name = "Visit_type")
    protected Integer visitType;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPersonId(BigInteger value) {
        this.personId = value;
    }

    /**
     * Gets the value of the directionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDirectionDate() {
        return directionDate;
    }

    /**
     * Sets the value of the directionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDirectionDate(XMLGregorianCalendar value) {
        this.directionDate = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the icdType property.
     * 
     */
    public int getIcdType() {
        return icdType;
    }

    /**
     * Sets the value of the icdType property.
     * 
     */
    public void setIcdType(int value) {
        this.icdType = value;
    }

    /**
     * Gets the value of the ocdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOcdCode() {
        return ocdCode;
    }

    /**
     * Sets the value of the ocdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOcdCode(String value) {
        this.ocdCode = value;
    }

    /**
     * Gets the value of the directionReason property.
     * 
     */
    public int getDirectionReason() {
        return directionReason;
    }

    /**
     * Sets the value of the directionReason property.
     * 
     */
    public void setDirectionReason(int value) {
        this.directionReason = value;
    }

    /**
     * Gets the value of the sendedMo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSendedMo() {
        return sendedMo;
    }

    /**
     * Sets the value of the sendedMo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSendedMo(BigInteger value) {
        this.sendedMo = value;
    }

    /**
     * Gets the value of the sendingMo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSendingMo() {
        return sendingMo;
    }

    /**
     * Sets the value of the sendingMo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSendingMo(BigInteger value) {
        this.sendingMo = value;
    }

    /**
     * Gets the value of the patientStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPatientStatus() {
        return patientStatus;
    }

    /**
     * Sets the value of the patientStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPatientStatus(Integer value) {
        this.patientStatus = value;
    }

    /**
     * Gets the value of the rpnIDMother property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRpnIDMother() {
        return rpnIDMother;
    }

    /**
     * Sets the value of the rpnIDMother property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRpnIDMother(BigInteger value) {
        this.rpnIDMother = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupId(Integer value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentId(BigInteger value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the serviceKind2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServiceKind2() {
        return serviceKind2;
    }

    /**
     * Sets the value of the serviceKind2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServiceKind2(Boolean value) {
        this.serviceKind2 = value;
    }

    /**
     * Gets the value of the refferalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefferalId() {
        return refferalId;
    }

    /**
     * Sets the value of the refferalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefferalId(String value) {
        this.refferalId = value;
    }

    /**
     * Gets the value of the visitType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVisitType() {
        return visitType;
    }

    /**
     * Sets the value of the visitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVisitType(Integer value) {
        this.visitType = value;
    }

}
