//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.eps;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import kz.ezdrav.eps_smartbridge_adapter.model.ws.EpsRequest;


/**
 * <p>Java class for ParamsIDs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParamsIDs"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Identifiers" type="{http://www.kaysat-ps.org}IDRecord" maxOccurs="unbounded"/&gt;
 *         &lt;element name="TypeRegistr" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParamsIDs", propOrder = {
    "identifiers",
    "typeRegistr"
})
public class ParamsIDs extends EpsRequest {

    @XmlElement(name = "Identifiers", required = true)
    protected List<IDRecord> identifiers;
    @XmlElement(name = "TypeRegistr")
    protected int typeRegistr;

    /**
     * Gets the value of the identifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDRecord }
     * 
     * 
     */
    public List<IDRecord> getIdentifiers() {
        if (identifiers == null) {
            identifiers = new ArrayList<IDRecord>();
        }
        return this.identifiers;
    }

    /**
     * Gets the value of the typeRegistr property.
     * 
     */
    public int getTypeRegistr() {
        return typeRegistr;
    }

    /**
     * Sets the value of the typeRegistr property.
     * 
     */
    public void setTypeRegistr(int value) {
        this.typeRegistr = value;
    }

}
