//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.14 at 04:24:58 PM GMT+05:00 
//


package kz.ezdrav.eps_smartbridge_adapter.model.ws.eps;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ServiceElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{http://www.kaysat-ps.org}ServiceID"/&gt;
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Customer" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="Performer" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="PatientID" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="PatientFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PatientLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PatientBirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="FinanceSourceID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="MKB10" type="{http://www.kaysat-ps.org}MKB10Code"/&gt;
 *         &lt;element name="DoctorFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DoctorLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Diag_list" type="{http://www.kaysat-ps.org}ChekList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceElement", propOrder = {
    "id",
    "date",
    "customer",
    "performer",
    "serviceID",
    "patientID",
    "patientFirstName",
    "patientLastName",
    "patientBirthDate",
    "financeSourceID",
    "mkb10",
    "doctorFirstName",
    "doctorLastName",
    "diagList"
})
public class ServiceElement {

    @XmlElement(name = "ID", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "Customer")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger customer;
    @XmlElement(name = "Performer", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger performer;
    @XmlElement(name = "ServiceID")
    protected long serviceID;
    @XmlElement(name = "PatientID")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger patientID;
    @XmlElement(name = "PatientFirstName")
    protected String patientFirstName;
    @XmlElement(name = "PatientLastName")
    protected String patientLastName;
    @XmlElement(name = "PatientBirthDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar patientBirthDate;
    @XmlElement(name = "FinanceSourceID")
    protected long financeSourceID;
    @XmlElement(name = "MKB10", required = true)
    protected String mkb10;
    @XmlElement(name = "DoctorFirstName")
    protected String doctorFirstName;
    @XmlElement(name = "DoctorLastName")
    protected String doctorLastName;
    @XmlElement(name = "Diag_list")
    protected List<ChekList> diagList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomer(BigInteger value) {
        this.customer = value;
    }

    /**
     * Gets the value of the performer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPerformer() {
        return performer;
    }

    /**
     * Sets the value of the performer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPerformer(BigInteger value) {
        this.performer = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     */
    public long getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     */
    public void setServiceID(long value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPatientID(BigInteger value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the patientFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientFirstName() {
        return patientFirstName;
    }

    /**
     * Sets the value of the patientFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientFirstName(String value) {
        this.patientFirstName = value;
    }

    /**
     * Gets the value of the patientLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientLastName() {
        return patientLastName;
    }

    /**
     * Sets the value of the patientLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientLastName(String value) {
        this.patientLastName = value;
    }

    /**
     * Gets the value of the patientBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPatientBirthDate() {
        return patientBirthDate;
    }

    /**
     * Sets the value of the patientBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPatientBirthDate(XMLGregorianCalendar value) {
        this.patientBirthDate = value;
    }

    /**
     * Gets the value of the financeSourceID property.
     * 
     */
    public long getFinanceSourceID() {
        return financeSourceID;
    }

    /**
     * Sets the value of the financeSourceID property.
     * 
     */
    public void setFinanceSourceID(long value) {
        this.financeSourceID = value;
    }

    /**
     * Gets the value of the mkb10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMKB10() {
        return mkb10;
    }

    /**
     * Sets the value of the mkb10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMKB10(String value) {
        this.mkb10 = value;
    }

    /**
     * Gets the value of the doctorFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorFirstName() {
        return doctorFirstName;
    }

    /**
     * Sets the value of the doctorFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorFirstName(String value) {
        this.doctorFirstName = value;
    }

    /**
     * Gets the value of the doctorLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorLastName() {
        return doctorLastName;
    }

    /**
     * Sets the value of the doctorLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorLastName(String value) {
        this.doctorLastName = value;
    }

    /**
     * Gets the value of the diagList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChekList }
     * 
     * 
     */
    public List<ChekList> getDiagList() {
        if (diagList == null) {
            diagList = new ArrayList<ChekList>();
        }
        return this.diagList;
    }

}
